#ifndef OOP_TYPE_H
#define OOP_TYPE_H

#include <stdint.h>

#include "type/type.h"

// oop/type.h — vexspoke's OWN class registry (the One Type Registry Law).
//
// The shared type ALGEBRA — the mask constants, SUGAR_VEX, FORM_*/PROJ_*/
// MOD_*/WRAP* constants, ARCH_*, Type_make/Type_class/Type_form/Type_project,
// the form/modifier/wrapper predicates, Type_arch, and the parent-chain
// resolver (Type_registerParents/Type_registerBareParents/Type_getParentClass/
// Type_isA) — is OWNED by Relational Engine in `type/type.h` and included
// above. The 16-byte block header lives with the allocator there too
// (MemoryHeader in nio/mem.h).
//
// This file keeps ONLY vexspoke's class numbers: the legacy 1-based ID_* list
// and the TYPE_* full-id macros built from it. Bare ID_* constants carry no
// project byte and name vexspoke's own class space only — cross-project
// dispatch ships full ids (PROJ_* | FORM_* | class). Other projects keep their
// own *-type.h and grant their parent chains through the RE algebra.

#define ID_INT          0x0001u
#define ID_LONG         0x0002u
#define ID_DOUBLE       0x0003u
#define ID_FIXED64      0x0004u
#define ID_FLOAT        0x0005u
#define ID_SHORT        0x0006u
#define ID_SPINLOCK     0x0007u
#define ID_RING_BUFFER  0x0008u
#define ID_BIT8         0x0009u
#define ID_BIT16        0x000Au
#define ID_BIT32        0x000Bu
#define ID_BIT64        0x000Cu
#define ID_VEC2         0x000Du
#define ID_VEC3         0x000Eu
#define ID_ENTITY       0x000Fu

// --- MATH / GEOMETRY CLASSES (added in the C port) ---
#define ID_VEC4        0x0029u
#define ID_MAT3        0x002Au
#define ID_MAT4        0x002Bu
#define ID_QUATERNION  0x002Cu
#define ID_POINT       0x002Du
#define ID_RECT        0x002Eu

// --- SCALAR / WRAPPER CLASSES (Legacy TypeRegister raw IDs) ---
#define ID_BYTE         0x0010u
#define ID_STRING       0x0011u
#define ID_INT_FLOAT    0x0012u
#define ID_INT_DOUBLE   0x0013u
#define ID_LONG_FLOAT   0x0014u
#define ID_LONG_DOUBLE  0x0015u
#define ID_VARIABLE     0x0016u
#define ID_PACK         0x0017u
#define ID_ARRAYS       0x0018u
#define ID_HASH         0x0019u
#define ID_CLASS        0x001Au
#define ID_STRIDE       0x001Bu
#define ID_FILE         0x0030u
#define ID_BOOL         0x0031u
#define ID_BRAIN        0x0032u
#define ID_FIXED32      0x0033u
#define ID_WS_CLIENT    0x0034u
#define ID_PROCESS_SPAWN 0x0035u
#define ID_STRING_POOL  0x0036u
#define ID_CIRCLE_ARRAY 0x0037u
#define ID_SPHERE_ARRAY 0x0038u
#define ID_OCTREE       0x0039u
#define ID_CRYPTO       0x003Au
#define ID_COMMAND      0x0064u

// --- COLLECTION CLASSES ---
#define ID_LIST              0x001Cu
#define ID_MAP               0x001Du
#define ID_SET               0x001Eu
#define ID_STACK             0x001Fu
#define ID_DEQUE             0x0020u
#define ID_MIN_HEAP          0x0021u
#define ID_SPARSE_SET        0x0022u
#define ID_RANDOM            0x0023u
#define ID_INDEX_RANDOM      0x0024u
#define ID_PROBABLE          0x0025u
#define ID_PROBABLE_OBJECTS  0x0026u
#define ID_QUEUE             0x0027u
#define ID_ARGUMENTS         0x0028u

// --- OBJECT WRAPPERS & MODIFIERS (Legacy 0x006F..0x0075) ---
#define ID_CHOICE     0x006Fu
#define ID_FUTURE     0x0070u
#define ID_PASSIVE    0x0071u
#define ID_REACTIVE   0x0072u
#define ID_TRANSIENT  0x0073u
#define ID_LOCAL      0x0074u
#define ID_GLOBAL     0x0075u

// --- BUFFER FAMILY (Legacy 0x4A / 0x50..0x63) ---
#define ID_BUFFER                  0x004Au
#define ID_ACCUMULUATION_BUFFER    0x0050u
#define ID_AMBIENT_BUFFER          0x0051u
#define ID_COLOR_BUFFER            0x0052u
#define ID_DEFAULT_PIXEL_BUFFER    0x0053u
#define ID_DEPTH_BUFFER            0x0054u
#define ID_FILTER_BUFFER           0x0055u
#define ID_FRAME_BUFFER            0x0056u
#define ID_HEIGHT_BUFFER           0x0057u
#define ID_LIGHT_BUFFER            0x0058u
#define ID_MATERIAL_RESOLVE        0x0059u
#define ID_MOTION_VECTOR_BUFFER    0x005Au
#define ID_NORMAL_BUFFER           0x005Bu
#define ID_PHYSICAL_BUFFER         0x005Cu
#define ID_POST_PROCESSING_BUFFER  0x005Du
#define ID_REFLECTIVITY_BUFFER     0x005Eu
#define ID_SHADOW_BUFFER           0x005Fu
#define ID_SPECULAR_BUFFER         0x0060u
#define ID_STENCIL_BUFFER          0x0061u
#define ID_TRANSPARENCY_BUFFER     0x0062u
#define ID_VISIBILITY_BUFFER       0x0063u

// --- SYSTEM CLASSES ---
#define ID_DISPLAY_MONITOR              0x0066u
#define TYPE_DISPLAY_MONITOR_SINGLETON  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_DISPLAY_MONITOR)

// --- THREAD CLASSES (the real OS threads; sync primitives live in atomic/) ---
#define ID_THREAD             0x0080u
#define ID_THREAD_NETWORKING  0x0081u
#define ID_THREAD_EVENT       0x0082u
#define ID_THREAD_DRAW        0x0083u
#define ID_THREAD_SCRIPTING   0x0084u
#define ID_THREAD_UI          0x0085u
// The thread block resumed past the later families: 0x0086..0x00A7 are taken
// (audio, input, reflection, the reactive scalars), so the two new roles append
// here rather than reuse a live id.
#define ID_THREAD_REACTIVE    0x00A8u
#define ID_THREAD_COMPUTE     0x00A9u

#define TYPE_THREAD_SINGLETON             (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD)
#define TYPE_THREAD_NETWORKING_SINGLETON  (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_NETWORKING)
#define TYPE_THREAD_EVENT_SINGLETON       (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_EVENT)
#define TYPE_THREAD_DRAW_SINGLETON        (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_DRAW)
#define TYPE_THREAD_SCRIPTING_SINGLETON   (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_SCRIPTING)
#define TYPE_THREAD_UI_SINGLETON          (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_UI)
#define TYPE_THREAD_REACTIVE_SINGLETON    (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_REACTIVE)
#define TYPE_THREAD_COMPUTE_SINGLETON     (SUGAR_VEX | PROJ_HOTCWAP | FORM_SINGLETON | ID_THREAD_COMPUTE)

// --- AUDIO CLASSES (native playback seam) ---
#define ID_AUDIO_CLIP   0x0086u
#define ID_AUDIO_VOICE  0x0087u
#define ID_AUDIO        0x0088u

#define TYPE_AUDIO_CLIP_SINGLETON   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_AUDIO_CLIP)
#define TYPE_AUDIO_VOICE_SINGLETON  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_AUDIO_VOICE)
#define TYPE_AUDIO_SINGLETON        (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_AUDIO)

// --- INPUT CLASSES (binding registry) ---
#define ID_KEY_MAP      0x0089u

#define TYPE_KEY_MAP_SINGLETON      (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_KEY_MAP)
#define TYPE_KEY_MAP_ARRAY          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_KEY_MAP)

// --- CONTAINER CLASSES (never-moved chunked storage) ---
#define ID_CHUNKED_LIST 0x008Au

#define TYPE_CHUNKED_LIST           (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_CHUNKED_LIST)

// --- EXCEPTION HANDLING ---
#define ID_EXCEPTION    0x008Bu

#define TYPE_EXCEPTION_SINGLETON    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_EXCEPTION)

// --- REFLECTION CLASSES (the 32-byte name box atom) ---
#define ID_VARIABLE_SLOT 0x008Cu
#define ID_VARIABLE_HASH_MAP 0x008Du
#define ID_SHELF 0x008Eu
#define ID_SHELF_NODE 0x008Fu
#define ID_SEGMENT_INDEX 0x0090u
#define ID_SEGMENT_ENTRY 0x0091u
#define ID_SEGMENT_POSTING 0x0092u
#define ID_VARIABLE_MINI_MAP 0x0093u
#define ID_REFLECT_CLASS 0x0094u
#define ID_REFLECT_FIELD 0x0095u
#define ID_REFLECT_VARIABLE 0x0096u
#define ID_REFLECT_METHOD 0x0097u
#define ID_REFLECT_STRUCT 0x0099u
#define ID_REACTIVE_BOOL 0x009Au
#define ID_REACTIVE_CHAR 0x009Bu
#define ID_REACTIVE_SHORT 0x009Cu
#define ID_REACTIVE_INT 0x009Du
#define ID_REACTIVE_LONG 0x009Eu
#define ID_REACTIVE_FLOAT 0x009Fu
#define ID_REACTIVE_DOUBLE 0x00A0u
#define ID_REACTIVE_STRING 0x00A1u
#define ID_REACTIVE_INT_FLOAT 0x00A2u
#define ID_REACTIVE_INT_DOUBLE 0x00A3u
#define ID_REACTIVE_LONG_FLOAT 0x00A4u
#define ID_REACTIVE_LONG_DOUBLE 0x00A5u
#define ID_REACTIVE_BYTE 0x00A6u
#define ID_REACTIVE_PROBABLE 0x00A7u

#define TYPE_VARIABLE_SLOT          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_VARIABLE_SLOT)
#define TYPE_VARIABLE_HASH_MAP      (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_VARIABLE_HASH_MAP)
#define TYPE_SHELF                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_SHELF)
#define TYPE_SEGMENT_INDEX          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_SEGMENT_INDEX)
#define TYPE_VARIABLE_MINI_MAP      (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_VARIABLE_MINI_MAP)
#define TYPE_REFLECT_CLASS          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_REFLECT_CLASS)
#define TYPE_REFLECT_FIELD          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_REFLECT_FIELD)
#define TYPE_REFLECT_VARIABLE       (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_REFLECT_VARIABLE)
#define TYPE_REFLECT_METHOD         (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_REFLECT_METHOD)
#define TYPE_REFLECT_STRUCT         (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_REFLECT_STRUCT)
#define TYPE_REACTIVE_BOOL          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_BOOL)
#define TYPE_REACTIVE_CHAR          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_CHAR)
#define TYPE_REACTIVE_SHORT         (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_SHORT)
#define TYPE_REACTIVE_INT           (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_INT)
#define TYPE_REACTIVE_LONG          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_LONG)
#define TYPE_REACTIVE_FLOAT         (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_FLOAT)
#define TYPE_REACTIVE_DOUBLE        (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_DOUBLE)
#define TYPE_REACTIVE_STRING        (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_STRING)
#define TYPE_REACTIVE_INT_FLOAT     (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_INT_FLOAT)
#define TYPE_REACTIVE_INT_DOUBLE    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_INT_DOUBLE)
#define TYPE_REACTIVE_LONG_FLOAT    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_LONG_FLOAT)
#define TYPE_REACTIVE_LONG_DOUBLE   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_LONG_DOUBLE)
#define TYPE_REACTIVE_BYTE          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE_BYTE)
#define TYPE_REACTIVE_PROBABLE      (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | WRAP2_PROBABLE | ID_REACTIVE_PROBABLE)

// --- DOWNSTREAM CLASS SPACE (owned per project, NOT listed here) ---
// Every project ships its own *-type.h registry and numbers its classes
// from 1: darling classes live in darling/c23/darling-type.h, graphvex in
// graphvex/src/graphvex/type.h, hotcwap module constants in
// hotcwap/oop/hotcwap-type.h. This file keeps vexspoke-owned IDs only, in the
// legacy 1-based list that predates the project byte (vexspoke primitives
// pass bare ids to the allocator's BitPool keyed by these numbers). Central
// logic must never include downstream ID files (upstream builds standalone) —
// parent chains resolve through the RE Type_registerParents seam, keyed by the
// project byte, never by class ranges. Thread constants stay here (vexspoke's
// thread.c may not include hotcwap) but carry PROJ_HOTCWAP in their TYPE_* macros.

#define TYPE_INT_SINGLETON  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_INT)
#define TYPE_INT_ARRAY      (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_INT)
#define TYPE_INT_POINTER    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_POINTER   | ID_INT)
#define TYPE_LONG_ARRAY     (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_LONG)
#define TYPE_FLOAT_ARRAY    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_FLOAT)
#define TYPE_DOUBLE_ARRAY   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_DOUBLE)
#define TYPE_BYTE_ARRAY     (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_BYTE)
#define TYPE_STRING_ARRAY   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_STRING)
#define TYPE_STRING_POOL    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_STRING_POOL)

#define TYPE_SPIN_LOCK               (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_SPINLOCK)
#define TYPE_RING_BUFFER             (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_RING_BUFFER)
#define TYPE_LIST                    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_LIST)
#define TYPE_ARRAY                   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_ARRAYS)
#define TYPE_CIRCLE_ARRAY            (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_CIRCLE_ARRAY)
#define TYPE_SPHERE_ARRAY            (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_SPHERE_ARRAY)
#define TYPE_OCTREE                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_STRUCT_SINGLETON | ID_OCTREE)
#define TYPE_CRYPTO                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_CRYPTO)
#define TYPE_VEC2_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_VEC2)
#define TYPE_VEC3_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_VEC3)
#define TYPE_VEC4_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_VEC4)
#define TYPE_MAT3_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_MAT3)
#define TYPE_MAT4_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_MAT4)
#define TYPE_QUATERNION_SINGLETON    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_QUATERNION)
#define TYPE_POINT_SINGLETON         (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_POINT)
#define TYPE_RECT_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_RECT)
#define TYPE_STACK                   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_STACK)
#define TYPE_DEQUE                   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_DEQUE)
#define TYPE_QUEUE                   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_QUEUE)
#define TYPE_MAP                     (SUGAR_VEX | PROJ_VEXSPOKE | FORM_POINTER   | ID_MAP)
#define TYPE_SET                     (SUGAR_VEX | PROJ_VEXSPOKE | FORM_POINTER   | ID_SET)
#define TYPE_MIN_HEAP                (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_MIN_HEAP)
#define TYPE_RANDOM                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_RANDOM)
#define TYPE_PROBABLE                (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP2_PROBABLE | ID_PROBABLE)
#define TYPE_PROBABLE_ARRAY          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | WRAP2_PROBABLE | ID_PROBABLE)
#define TYPE_PROBABLE_OBJECTS_ARRAY  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | WRAP2_PROBABLE_OBJECTS | ID_PROBABLE_OBJECTS)
#define TYPE_CHOICE                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP2_CHOICE | ID_CHOICE)
#define TYPE_CHOICE_ARRAY            (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | WRAP2_CHOICE | ID_CHOICE)
#define TYPE_FUTURE                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP2_FUTURE | ID_FUTURE)
#define TYPE_FUTURE_ARRAY            (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | WRAP2_FUTURE | ID_FUTURE)
#define TYPE_GLOBAL                  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | MOD_GLOBAL | ID_GLOBAL)
#define TYPE_GLOBAL_ARRAY            (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | MOD_GLOBAL | ID_GLOBAL)
#define TYPE_LOCAL                   (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | MOD_LOCALE | ID_LOCAL)
#define TYPE_LOCAL_ARRAY             (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | MOD_LOCALE | ID_LOCAL)
#define TYPE_PASSIVE                 (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_PROACTIVE | ID_PASSIVE)
#define TYPE_PASSIVE_ARRAY           (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | WRAP_PROACTIVE | ID_PASSIVE)
#define TYPE_REACTIVE                (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP_REACTIVE | ID_REACTIVE)
#define TYPE_REACTIVE_ARRAY          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY | WRAP_REACTIVE | ID_REACTIVE)
#define TYPE_PROBABLE_OBJECTS        (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | WRAP2_PROBABLE_OBJECTS | ID_PROBABLE_OBJECTS)
#define TYPE_FILE_SINGLETON          (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_FILE)
#define TYPE_WS_CLIENT_SINGLETON     (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_WS_CLIENT)
#define TYPE_PROCESS_SPAWN_SINGLETON (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_PROCESS_SPAWN)
#define TYPE_COMMAND_SINGLETON       (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_COMMAND)

#define TYPE_INT_SINGLETON  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_INT)
#define TYPE_INT_ARRAY      (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_INT)
#define TYPE_INT_POINTER    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_POINTER   | ID_INT)

#define TYPE_SPIN_LOCK    (SUGAR_VEX | PROJ_VEXSPOKE | FORM_SINGLETON | ID_SPINLOCK)
#define TYPE_RING_BUFFER  (SUGAR_VEX | PROJ_VEXSPOKE | FORM_ARRAY     | ID_RING_BUFFER)

#endif
