#ifndef SYSTEM_CAPTURE_TOOL_H
#define SYSTEM_CAPTURE_TOOL_H

#include <stdbool.h>
#include <stdint.h>

// system/capture_tool.h — screen/audio capture & streaming probe (darwin).
//
// Answers "is the machine capturing RIGHT NOW" at the level the OS lets
// us see: a registry of known capture-capable tools (OBS, QuickTime
// Player, the macOS screenshot utility, Screen Studio, ...) plus
// per-tool liveness probes. "OBS is running" ≈ someone could be
// recording; macOS hides the true system-wide privacy state by design
// (no public API reveals another app's active ScreenCaptureKit session),
// so the honest contract is tool-liveness, not a recording flag — see
// ;;INTENTION.
//
// KIND: coarsest wire bucket — screen recording, streaming, or audio
// capture. DRIVER rows (BlackHole, Soundflower) have no process: they
// are CoreAudio HAL plugins and are probed by scanning the plugin
// directory instead.

typedef enum CaptureKind {
    CAPTURE_KIND_SCREEN, // screen/video recording
    CAPTURE_KIND_STREAM, // live streaming (OBS stream mode, Zoom, ...)
    CAPTURE_KIND_AUDIO,  // audio capture (Voice Memos, virtual devices)
} CaptureKind;

// SLOT RECORD (owned by CaptureTool, Rule 3 co-location): one capture-capable
// tool. Immutable rows live in capture_tool.c; all behavior hangs off the
// CaptureTool table class.
typedef struct CaptureSlot {
    const char *slug;        // canonical key, e.g. "obs"
    const char *displayName; // human label, e.g. "OBS Studio"
    const char *procKey;     // executable basename to probe; NULL = driver row
    const char *driverDir;   // plugin dir to scan; NULL = process row
    CaptureKind kind;        // screen / stream / audio
    const char *note;        // caveat; NULL when none
} CaptureSlot;

// The table class — singleton handle; state lives in static const rows
// generated by hand under src/system/data/.
typedef struct CaptureTool {
    uint32_t reserved; // signature/marker; no mutable state
} CaptureTool;

// --- Constructor ---
// Returns the shared directory handle (static, zero-init, never NULL).
CaptureTool *CaptureTool_shared(void);

// --- Core functions ---
// Total rows. Null-safe: 0 on NULL self.
uint32_t CaptureTool_count(const CaptureTool *self);
// Row at index i (hand-curated order). NULL when out of range.
const CaptureSlot *CaptureTool_at(const CaptureTool *self, uint32_t i);
// Row by canonical slug. NULL when absent. Linear scan (~15 rows).
const CaptureSlot *CaptureTool_get(const CaptureTool *self, const char *slug);
// true when the tool's process is alive right now (process rows) or when
// its driver is loaded (driver rows — kernel/audio plugin presence).
bool CaptureTool_isInstalled(const CaptureTool *self, const CaptureSlot *slot);
// true when the tool's PROCESS is alive right now. Always false for
// driver rows (they have no process). The "recording right now" proxy.
bool CaptureTool_isRunning(const CaptureTool *self, const CaptureSlot *slot);
// How many tools of one kind are running right now (screen/stream/audio).
uint32_t CaptureTool_countRunning(const CaptureTool *self, CaptureKind kind);
// How many tools of any kind are running right now.
uint32_t CaptureTool_countRunningAll(const CaptureTool *self);

// --- Getters (Rule 24; null-safe; setters omitted — immutable rows) ---
const char *CaptureTool_getSlug(const CaptureTool *self, const CaptureSlot *slot);
const char *CaptureTool_getDisplayName(const CaptureTool *self, const CaptureSlot *slot);
const char *CaptureTool_getProcKey(const CaptureTool *self, const CaptureSlot *slot);
const char *CaptureTool_getDriverDir(const CaptureTool *self, const CaptureSlot *slot);
CaptureKind CaptureTool_getKind(const CaptureTool *self, const CaptureSlot *slot);
const char *CaptureTool_getNote(const CaptureTool *self, const CaptureSlot *slot);

#endif