package buffers;

import annotation.Draft;
import annotation.Required;
import annotation.Unsafe;
import annotation.Volatile;
import oop.TypeRegister;

@Draft
public final class PhysicalBuffer {

    @Required
    public static final int CLASS_ID = TypeRegister.ID_PHYSICAL_BUFFER;

    private PhysicalBuffer() {}

    public static int channels() {
        return 4;
    }

    public static long allocate(int width, int height) {
        return Buffer.allocate(CLASS_ID, width, height, channels());
    }

    public static long expand(long oldPointer, int newWidth, int newHeight) {
        return Buffer.expand(oldPointer, newWidth, newHeight);
    }

    public static void free(long pointer) {
        Buffer.free(pointer);
    }

    public static int width(long pointer) {
        return Buffer.width(pointer);
    }

    public static int height(long pointer) {
        return Buffer.height(pointer);
    }

    public static int channels(long pointer) {
        return Buffer.channels(pointer);
    }

    public static long get(long pointer) {
        return Buffer.get(pointer);
    }

    public static long get(long pointer, int index) {
        return Buffer.get(pointer, index);
    }

    public static void set(long pointer, long value) {
        Buffer.set(pointer, value);
    }

    public static void set(long pointer, int index, long value) {
        Buffer.set(pointer, index, value);
    }

    @Volatile
    public static long getVolatile(long pointer) {
        return Buffer.getVolatile(pointer);
    }

    @Volatile
    public static void setVolatile(long pointer, long value) {
        Buffer.setVolatile(pointer, value);
    }

    public static boolean compareAndSet(long pointer, long expected, long value) {
        return Buffer.compareAndSet(pointer, expected, value);
    }

    public static long getAndSet(long pointer, long value) {
        return Buffer.getAndSet(pointer, value);
    }

    public static int type(long pointer) {
        return Buffer.type(pointer);
    }

    public static int length(long pointer) {
        return Buffer.length(pointer);
    }

    public static int classId(long pointer) {
        return Buffer.classId(pointer);
    }

    public static boolean isArray(long pointer) {
        return Buffer.isArray(pointer);
    }

    // --- AUTOGENERATED UNSAFE & VOLATILE VARIANTS ---

    @Unsafe
    public static long unsafeGet(long pointer) {
        return Buffer.unsafeGet(pointer);
    }

    @Unsafe
    public static long unsafeGet(long pointer, int index) {
        return Buffer.unsafeGet(pointer, index);
    }

    @Unsafe
    public static void unsafeSet(long pointer, long value) {
        Buffer.unsafeSet(pointer, value);
    }

    @Unsafe
    public static void unsafeSet(long pointer, int index, long value) {
        Buffer.unsafeSet(pointer, index, value);
    }

    @Volatile
    public static long getVolatile(long pointer, int index) {
        return Buffer.getVolatile(pointer, index);
    }

    @Volatile
    public static void setVolatile(long pointer, int index, long value) {
        Buffer.setVolatile(pointer, index, value);
    }

    @Unsafe
    @Volatile
    public static long unsafeVolatileGet(long pointer) {
        return Buffer.unsafeVolatileGet(pointer);
    }

    @Unsafe
    @Volatile
    public static long unsafeVolatileGet(long pointer, int index) {
        return Buffer.unsafeVolatileGet(pointer, index);
    }

    @Unsafe
    @Volatile
    public static void unsafeVolatileSet(long pointer, long value) {
        Buffer.unsafeVolatileSet(pointer, value);
    }

    @Unsafe
    @Volatile
    public static void unsafeVolatileSet(long pointer, int index, long value) {
        Buffer.unsafeVolatileSet(pointer, index, value);
    }
}
