package buffers;

import annotation.Draft;
import annotation.Required;
import annotation.Unsafe;
import annotation.Volatile;
import oop.TypeRegister;

@Draft
public final class ReflectivityBuffer {

    @Required
    public static final int CLASS_ID = TypeRegister.ID_REFLECTIVITY_BUFFER;

    private ReflectivityBuffer() {}

    public static int channels() {
        return 1;
    }

    public static long allocateSingleton() {
        return Buffer.allocateSingleton(CLASS_ID);
    }

    public static long allocateArray(int length) {
        return Buffer.allocateArray(CLASS_ID, length);
    }

    public static long allocateMatrix(int length) {
        return Buffer.allocateMatrix(CLASS_ID, length);
    }

    public static long expandArray(long oldPointer, int newLength) {
        return Buffer.expandArray(oldPointer, newLength);
    }

    public static long expandMatrix(long oldPointer, int newLength) {
        return Buffer.expandMatrix(oldPointer, newLength);
    }

    public static void free(long pointer) {
        Buffer.free(pointer);
    }

    public static long get(long pointer) {
        return Buffer.get(pointer);
    }

    public static long get(long pointer, int index) {
        return Buffer.get(pointer, index);
    }

    public static long getPointer(long matrixPointer, int index) {
        return Buffer.getPointer(matrixPointer, index);
    }

    public static void set(long pointer, long value) {
        Buffer.set(pointer, value);
    }

    public static void set(long pointer, int index, long value) {
        Buffer.set(pointer, index, value);
    }

    @Volatile
    public static long getVolatile(long pointer) {
        return Buffer.getVolatile(pointer);
    }

    @Volatile
    public static void setVolatile(long pointer, long value) {
        Buffer.setVolatile(pointer, value);
    }

    public static boolean compareAndSet(long pointer, long expected, long value) {
        return Buffer.compareAndSet(pointer, expected, value);
    }

    public static long getAndSet(long pointer, long value) {
        return Buffer.getAndSet(pointer, value);
    }

    public static void setPointer(long matrixPointer, int index, long targetPointer) {
        Buffer.setPointer(matrixPointer, index, targetPointer);
    }

    public static int type(long pointer) {
        return Buffer.type(pointer);
    }

    public static int length(long pointer) {
        return Buffer.length(pointer);
    }

    public static int classId(long pointer) {
        return Buffer.classId(pointer);
    }

    public static boolean isSingleton(long pointer) {
        return Buffer.isSingleton(pointer);
    }

    public static boolean isArray(long pointer) {
        return Buffer.isArray(pointer);
    }

    public static boolean isPointer(long pointer) {
        return Buffer.isPointer(pointer);
    }

    // --- AUTOGENERATED UNSAFE & VOLATILE VARIANTS ---

    @Unsafe
    public static long unsafeGet(long pointer) {
        return Buffer.unsafeGet(pointer);
    }

    @Unsafe
    public static long unsafeGet(long pointer, int index) {
        return Buffer.unsafeGet(pointer, index);
    }

    @Unsafe
    public static long unsafeGetPointer(long matrixPointer, int index) {
        return Buffer.unsafeGetPointer(matrixPointer, index);
    }

    @Unsafe
    public static void unsafeSet(long pointer, long value) {
        Buffer.unsafeSet(pointer, value);
    }

    @Unsafe
    public static void unsafeSet(long pointer, int index, long value) {
        Buffer.unsafeSet(pointer, index, value);
    }

    @Unsafe
    public static void unsafeSetPointer(long matrixPointer, int index, long targetPointer) {
        Buffer.unsafeSetPointer(matrixPointer, index, targetPointer);
    }

    @Volatile
    public static long getVolatile(long pointer, int index) {
        return Buffer.getVolatile(pointer, index);
    }

    @Volatile
    public static long getPointerVolatile(long matrixPointer, int index) {
        return Buffer.getPointerVolatile(matrixPointer, index);
    }

    @Volatile
    public static void setVolatile(long pointer, int index, long value) {
        Buffer.setVolatile(pointer, index, value);
    }

    @Volatile
    public static void setPointerVolatile(long matrixPointer, int index, long targetPointer) {
        Buffer.setPointerVolatile(matrixPointer, index, targetPointer);
    }

    @Unsafe
    @Volatile
    public static long unsafeVolatileGet(long pointer) {
        return Buffer.unsafeVolatileGet(pointer);
    }

    @Unsafe
    @Volatile
    public static long unsafeVolatileGet(long pointer, int index) {
        return Buffer.unsafeVolatileGet(pointer, index);
    }

    @Unsafe
    @Volatile
    public static long unsafeVolatileGetPointer(long matrixPointer, int index) {
        return Buffer.unsafeVolatileGetPointer(matrixPointer, index);
    }

    @Unsafe
    @Volatile
    public static void unsafeVolatileSet(long pointer, long value) {
        Buffer.unsafeVolatileSet(pointer, value);
    }

    @Unsafe
    @Volatile
    public static void unsafeVolatileSet(long pointer, int index, long value) {
        Buffer.unsafeVolatileSet(pointer, index, value);
    }

    @Unsafe
    @Volatile
    public static void unsafeVolatileSetPointer(long matrixPointer, int index, long targetPointer) {
        Buffer.unsafeVolatileSetPointer(matrixPointer, index, targetPointer);
    }
}
